### ISSUE TITLE
cannot get collect candy

### ISSUE THREAD

**Issue by mellow8** [Ondkloss/cg-candy-collector#2]
cannot get collect candy

**Comment by Ondkloss** [comment]
Thanks for your report @mellow8! I've submitted version 1.0.3 for review/publishing in Chrome and Firefox.
I've tested that it works locally for collecting a single day. If you still have any trouble after updating to 1.0.3, please tell!
If I don't hear anything (or experience anything myself) for the next couple of days I will close the issue.

**Comment by Ondkloss** [comment]
Version 1.0.3, which attempted to address this did not work properly. It worked when entering claim website, but not crossing into a new day.

Version 1.0.4, just submitted to Chrome/Firefox should do the trick. I'll still monitor for a couple of days, but I expect this one to solve it.

**Comment by Ondkloss** [comment]
With version 1.0.4 I consider this solved. Thanks for the report!
